# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ "main" ]
    paths:
      - src/aleimi/**
      - tests/**
      - pyproject.toml
      - .github/workflows/tests.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - src/aleimi/**
      - tests/**
      - pyproject.toml
      - .github/workflows/tests.yml

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, 'windows-latest'] #windows-latest (vina is not available for windows in conda-forge),m think about use bioconda autodock-vina
        python-version: [3.8, 3.9, '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies from conda
      run: |
        conda install -y -c conda-forge mopac
    - name: Install pip dependencies and aleimi on test mode
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -e .[test]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/aleimi --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/aleimi --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        echo after "Lint with flake8" My python version is actually: $(python --version).
    - name: Test with pytest
      run: |
        pytest --cov src/aleimi
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
